### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by knadh** [bumi/listmonk-heroku#10]
Hi @bumi. Finally managed to write a Heroku buildpack that automatically pulls and installs the latest listmonk release. The source is available here: https://github.com/knadh/listmonk-heroku

I've already replaced the Heroku button on the listmonk README. As that is the correct way to install the app without having to hardcode the binary in the repo, I think you should archive this repository and leave a note for users coming by.

Thank you for the effort!

**Comment by bumi** [comment]
@knadh you're awesome! that's great. sorry that I never managed to get back to this.
