### ISSUE TITLE
Hekuro deployment issue

### ISSUE THREAD

**Issue by Nezaros** [bumi/listmonk-heroku#2]
Hello
I tried to deploy it on Heroku but not worked I can't figure out the correct config...can you please add me to the deployment app in Heroku to learn how your config is work or make a new one and transfer it to please. my email is nezarmebrouk@gmail.com.
Thanks

**Comment by bumi** [comment]
You can find the configuration options here: https://github.com/knadh/listmonk/wiki/Configuration#environment-variables

This Heroku documentation explains how to set environment variables for your Heroku app: https://devcenter.heroku.com/articles/config-vars

If you can specify what exactly did not work I can try to help you debug your settings.

**Comment by Nezaros** [comment]
I posted it here
https://github.com/knadh/listmonk/issues/77

**Comment by bumi** [comment]
But that does not look like you are using this deploy button for [Heroku](https://heroku.com/) and deploy listmonk to heroku.

**Comment by Nezaros** [comment]
> But that does not look like you are using this deploy button for [Heroku](https://heroku.com/) and deploy listmonk to Heroku.

Yes I mean I doubt that this code have bugs I just want to see it in action can you give me a hand help.

**Comment by bumi** [comment]
Signup for heroku (it's free) and use this deploy button. You simply have to fill out a few basic fields. 
If you want to just have a look then you don't need to provide config options like: `LISTMONK_upload__s3__aws_access_key_id`

`APP_PASSWORD`, `APP_USERNAME`, `LISTMONK_from_email`, `LISTMONK_root` (=your heroku domain) is enough.

**Comment by Nezaros** [comment]
![Capture](https://user-images.githubusercontent.com/10624453/78297975-0ff84e80-7531-11ea-9f97-3d108eadb176.PNG)

**Comment by bumi** [comment]
what did you enter in the form as configuration?

**Comment by bumi** [comment]
closing this, feel free to open it again if you still have this issue.
