### ISSUE TITLE
Run scripts & scale dynos fails

### ISSUE THREAD

**Issue by Kickbykick** [bumi/listmonk-heroku#7]
I am new to deploying an app on heroku and I seem to be doing everything right but the one button click setup doesn't work.

It fails at "Run scripts & scale dynos" 
This is the error message I see:
`[1mTraceback[m (most recent call last):
	5: from /usr/bin/erb:175:in `<main>'
	4: from /usr/bin/erb:154:in `run'
	3: from /usr/lib/ruby/2.7.0/erb.rb:890:in `run'
	2: from /usr/lib/ruby/2.7.0/erb.rb:905:in `result'
	1: from /usr/lib/ruby/2.7.0/erb.rb:905:in `eval'
config/listmonk.toml.erb:11:in `<main>': [1muninitialized constant URI ([1;4mNameError[m[1m)[m` 

Please help.
Thanks.

![listmonk_heroku_bug](https://user-images.githubusercontent.com/25256595/104798281-015ee900-578b-11eb-83dd-c5033dcaa90e.PNG)

**Comment by bumi** [comment]
That is strange. 
Can you try it again? I made a change to see what's the reason.

**Comment by Kickbykick** [comment]
Thanks a lot, it works now : ).

**Comment by abriosi** [comment]
Hi,

I'm having the same problem but for different reasons.

Can you help me?

![image](https://user-images.githubusercontent.com/23288462/107238614-f6147b80-6a1f-11eb-8f7a-37b8ef5e1ce8.png)

```
2021/02/08 14:44:53 main.go:64: v0.7.0-alpha (0f055ea 2020-08-09T14:44:45Z)
2021/02/08 14:44:53 init.go:91: reading config: config/listmonk.toml
2021/02/08 14:44:53 init.go:167: connecting to db: ec2-54-74-14-109.eu-west-1.compute.amazonaws.com:5432/d8ar9nb3010smn

** first time installation **
** IMPORTANT: This will wipe existing listmonk tables and types in the DB 'd8ar9nb3010smn' **
2021/02/08 14:44:54 install.go:51: error loading SQL queries: Error preparing query 'next-campaign-subscribers': pq: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
```

**Comment by bumi** [comment]
are you using the latest master here? and can you provide the full log?

**Comment by bumi** [comment]
also just updated listmonk and made a minor config change, but that should not have any effects. 
your error looks strange. wondering why it says it had an SQL error.

**Comment by abriosi** [comment]
I'm simply clicking on this button and trying to deploy in Europe.

![image](https://user-images.githubusercontent.com/23288462/107288261-1150ac80-6a5b-11eb-8bce-f5bd7f5d0155.png)

Let me check if I can get you that full log

**Comment by abriosi** [comment]
App has deployed successfully. Thanks

**Comment by bumi** [comment]
great!
