### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by jacobhq** [bumi/listmonk-heroku#9]
Having read issue #8, I'm not sure how to upgrade. I've tried pushing the container, but I just get `No images to push`, and when I run `docker-compose build` I get this:

```
db uses an image, skipping
app uses an image, skipping
demo-db uses an image, skipping
demo-app uses an image, skipping
```

Any help would be appriciated.

**Comment by bumi** [comment]
not sure what you are doing with docker-compose? there is no docker involved in this heroku setup.

but you should simply pull the repository from heroku (so a very new repository folder on your computer) there you change the listmonk binary (and other settings if wanted/needed) and then you simply push again to heroku.

**Comment by jacobhq** [comment]
Oh ok, thanks.
